### ISSUE TITLE
username not shared with sshnp on with Python version of sshnpd

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#1024]
### Describe the bug

If running the pyton version of sshnpd and specifying `-u` the username is not shared with the client/manager atSign.

### Steps to reproduce

1. Install python version of sshnpd
2.  run with the following arguments `./sshnpdpy -m @cconstab -a @ssh_1 -d servalanpy -u `
3. And then run the sshnp to connect `sshnp -f @cconstab -t @ssh_1 -h @rv_am -d servalanpy --no-ad --no-et`
4. See error message
5. 

### Expected behavior

should work

### Screenshots

```
╰$ sshnp -f @cconstab -t @ssh_1 -h @rv_am -d servalanpy --no-ad --no-et
2024-05-02 11:59:18.844199 : Sending daemon feature check request
2024-05-02 11:59:18.844293 : Resolving remote username for user session

Error: Remote username record not shared with the client
```

**Comment by cpswan** [comment]
Docs updated at https://github.com/atsign-foundation/noports/pull/1048 to reflect that username must be specified.

We could potentially do more. Moving to discussion item.

**Comment by cpswan** [comment]
Let's have the discussion in PR92, though given progress with C daemon we shall probably not expend extra effort on Python.

**Comment by cpswan** [comment]
Discussion didn't happen in PR92, bumping to PR93

**Comment by Xlin123** [comment]
Discussed this ticket 08/06 in arch, conclusion was to close this ticket in light of the work that has been done on the C daemon.
