### ISSUE TITLE
Reduce notification expiry time from 24hours to 1 minute

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1091]
- Heavy usage of sshnp may cause a backlog of notifications which should be short-lived but the ttln defaults to 24h
- Most synchronous waiting periods will timeout after 10-15 seconds, so 30 should be more than long enough.
  - [gkc] let's go for 1 minute, just in case we need a little headroom

**Comment by cconstab** [comment]
Is the suggestion to have the option to set the notification time out?

**Comment by gkc** [comment]
No. Unrelated. This is about reducing ttl on notifications so they get cleaned up sooner and don't clog up server memory

**Comment by gkc** [comment]
[edited] Yes. This is about reducing ttl on NoPorts notifications so they get cleaned up sooner and don't clog up server memory

**Comment by gkc** [comment]
I'll pick this up as I'm familiar with the code and there are changes that need to be made in multiple places
