### ISSUE TITLE
bug (c sshnpd): list-devices not showing C daemon devices

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1115]
- missing device entries for the C daemon with --list-devices

**Comment by xavierchanth** [comment]
There's a file called background_jobs.c, the puts in that file are showing up when I scan with at-repl, but when I `sshnp -f @<client> --ls` they don't show up.

**Comment by xavierchanth** [comment]
Also related to the same function: username is not being shared to the client.

**Comment by JeremyTubongbanua** [comment]
I can pick this up this sprint (PR90)

Will also try to fix the issue where atclient_atkey memory is allocated in the fork'd thread that is not cleared

**Comment by xavierchanth** [comment]
Thanks, yeah maybe we pre-allocate that memory in the main thread so it can be freed there instead. However one caveat, this memory is not constant size, it is proportional to the number of managers which can be found in the sshnpd_params struct.

**Comment by JeremyTubongbanua** [comment]
> o it can be freed there instead. However one caveat, this memory is not constant size, it is proportional to the number of ma

Thanks 👍🏼 I was thinking of pre-allocating the memory before entering the thread..
