### ISSUE TITLE
Installation Issue - bad CPU type in executable: sshnp 

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/noports#1140]
### Describe the bug

When installing client side np, installation occurs as expected, however, when running
`sshnp -f @sys_client -t @ufw_pi_device -h @rv_am -d ufw_pi -i <~/.ssh/id_ed25519 -s`
it outputs:
`zsh: bad CPU type in executable: sshnp`

### Steps to reproduce

1. First run curl installation
2. Then run `chmod u+x universal.sh` and `./universal.sh`
3. And then run `sshnp`

### Expected behavior

Connect to configured sshnp device 

### Screenshots

<img width="277" alt="env" src="https://github.com/atsign-foundation/noports/assets/66637408/24a692a8-b430-4d87-be01-d7f254100eb5">
<img width="570" alt="uname" src="https://github.com/atsign-foundation/noports/assets/66637408/857eba39-78ca-4eb5-9380-85bc51b7f727">

### Smartphones

- Device: Mac
- OS: MacOSx64

**Comment by xavierchanth** [comment]
Can you run the following and post the logs:

```bash
mkdir -p /tmp/testnoports
cd /tmp/testnoports
curl -L https://github.com/atsign-foundation/noports/releases/download/v5.3.0/sshnp-macos-x64.zip -o sshnp-macos-x64.zip
unzip sshnp-macos-x64.zip
sshnp/sshnp --help
```

To cleanup after:
```
rm sshnp-macos-x64.zip
rm -rf sshnp/
```

**Comment by TylerTrott** [comment]
<img width="859" alt="Screenshot 2024-06-18 at 1 57 45 PM" src="https://github.com/atsign-foundation/noports/assets/66637408/68d9599a-a3d9-4e92-8a5d-e6f5e9d68a17">

**Comment by Xlin123** [comment]
GitHub making a breaking change... https://github.com/atsign-foundation/noports/pull/1144
