### ISSUE TITLE
ci (multibuild.yaml): Sanity check binaries

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1143]
Run --help for each binary to ensure that it was linked properly for the platform before bundling & uploading.

**Comment by Xlin123** [comment]
to prevent stuff like #1144

**Comment by xavierchanth** [comment]
Actually, this wouldn't even help with #1144, since the problem was that the runner was the wrong architecture in the first place, so the binary would still work just fine.

**Comment by xavierchanth** [comment]
Maybe it's still useful for ensuring that at least the binary executes, but the `dart compile` tool should (I would hope) exit with a non-zero exit code if the binary is malformed in some way.
