### ISSUE TITLE
Walkthroughs and release of APKAM documentation for Noports

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1159]
Walkthrough an APKAM installation, fixing / addressing any issues we encounter along the way.

Things we should be able to do:

- [x] Works e2e with a fresh pair of keys
- [x] Multiple device APKAM installations works
- [x] Secondary client with APKAM installation works

**Comment by xavierchanth** [comment]
Giving a generous 5 SP to account for multiple walkthroughs + potential issues

**Comment by xavierchanth** [comment]
Generic APKAM documentation for the widgets may also help with this documentation

**Comment by Xlin123** [comment]
![Image](https://github.com/atsign-foundation/noports/assets/42496953/c177e05e-0f28-4a42-b2d0-518a58d2c58e)

My fedora setup is forcing password authentication. Otherwise mutiple device on APKAM work.

**Comment by Xlin123** [comment]
I can merge the documentation, on APKAM now, but once [this ticket](https://github.com/atsign-foundation/at_libraries/issues/601) gets closed I'd like to update the documentation to something easier.


Thoughts on making "activate your atsign" a subpage inside basic installation? We can put it in the prerequisites section of the installation. 

Right now the installation page has 3 separate sections of different activations and honestly even I'm confused.

If we can separate the apkam enrollment and the atsign activation in the peoples brains I think we will have less confusion in the future,
