### ISSUE TITLE
Provide ability to use no-encrypt-traffic in npt

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/noports#1181]
### Is your feature request related to a problem? Please describe.

Sometimes users may not want to use encrypted sockets - perhaps for example they are using a protocol which already uses encryption. This always has to be used with appropriate user caution

### Describe the solution you'd like

Always encrypt by default; if user requests no encryption then show a prominent warning

**Comment by sitaram-kalluri** [comment]
Completed the code changes in no-ports and added a E2E test. Pending work is to run the E2E test and merge the PR.
