### ISSUE TITLE
C SSHNPD - keep alive with npt support

### ISSUE THREAD

**Issue by kdimick** [atsign-foundation/noports#1288]
### Describe the bug

I am trying to use NPT with the FreeBSD SSHNPD binary on my OPNsense firewall. Normally I set a timeout value on the CLI of the NPT but I get an error when I use the following command to connect to the OPNsense firewall. The --timeout within the command line to a Linux system running SSHNPD works fine. Should NPT using the "--timeout" variable be supported in the FreeBSD SSHNPD binary?

/Users/<my-home-directory>/.local/bin/npt --from @intense56 --to @55commercial --srvd @rv_am --device opnsense --timeout 90s --remote-port 22 --local-port 65221

--Error message output from the connection process---

Error : This device daemon does not support the 'timeout' value in npt session requests

### Steps to reproduce

1. First I installed the FreeBSD binary on my OPNsense firewall runnversion 24.7.1
2. Then I used the command "npt --from @intense56 --to @55commercial --srvd @rv_am --device opnsense --timeout 90s --remote-port 22 --local-port 65221"  to connect a NPT session the my OPNsense firewall.
3. And then I saw the message "Error : This device daemon does not support the 'timeout' value in npt session requests" in the terminal window.

### Expected behavior

I expected the npt session to connect as it does when connecting to a Linux running NoPorts 5.5.0 SSHNPD.

**Comment by cpswan** [comment]
@kdimick raised this with me in chat, and I asked him to open this issue.

I _think_ the problem here is that the FreeBSD binary is C sshnpd, which doesn't yet implement the `--timeout` feature

**Comment by gkc** [comment]
> @kdimick raised this with me in chat, and I asked him to open this issue.
> 
> I _think_ the problem here is that the FreeBSD binary is C sshnpd, which doesn't yet implement the `--timeout` feature

Yep that's correct, Chris

**Comment by xavierchanth** [comment]
See #1110 for the dart implementation of this feature.

**Comment by xavierchanth** [comment]
Closing as there's no actionable work here that isn't covered by another issue
