### ISSUE TITLE
Automate signing of MacOS binaries

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#137]
### Is your feature request related to a problem? Please describe.

@cconstab is presently having to manually sign binaries for MacOS using the process documented [here](https://docs.google.com/document/d/1j0oGdWWSkpceiyWbBQRX9vOborW2V5_-SUg9f0EXa5U/edit#heading=h.2bl6sbyrlr0r)

### Describe the solution you'd like

A script that can be run in GitHub Actions using a cert (and private key?) stored in GitHub Secrets

### Describe alternatives you've considered

Codemagic might have a canned approach to this?

**Comment by xavierchanth** [comment]
It is as automated as it gets, I don't see a point in trying to automate any further since we have to build for apple silicon anyways. Automating any further won't save us any time until GitHub supports apple silicon runners
