### ISSUE TITLE
Device name '-d' to accept '-' and to accept uppercase but to lowercase everything.

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#1403]
### Is your feature request related to a problem? Please describe.

People using NoPorts often use upper case and the '-' symbol for device names and the max length of a device is set to accpet uuid's but uuid's contain '-' which currently is not accepted as the fiel is strick snake case currentluy.

### Describe the solution you'd like

to accept upper case but to lowercase the name and to accept '-' whilst this is not strickly snake case

### Describe alternatives you've considered

keeping as is ... But this item trips many people up as it stands

**Comment by gkc** [comment]
Made P1 as this is tripping up customers

**Comment by xavierchanth** [comment]
Note: as is the default right now (I believe, need to verify code)

The leading char must be `[a-zA-z]` we especially don't want a leading `-` for command line parsing reasons.

**Comment by cconstab** [comment]
Thats fine, not seen anyone do that
