### ISSUE TITLE
Fix code scanning alert - Pinned-Dependencies (npm)

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#1411]
Tracking issue for:
- [x] https://github.com/atsign-foundation/noports/security/code-scanning/24
- [x] https://github.com/atsign-foundation/noports/security/code-scanning/25
- [x] https://github.com/atsign-foundation/noports/security/code-scanning/26

Fixed the above but also got these, which also have now been fixed
- [x] https://github.com/atsign-foundation/noports/security/code-scanning/30
- [x] https://github.com/atsign-foundation/noports/security/code-scanning/31
- [x] https://github.com/atsign-foundation/noports/security/code-scanning/32

**Comment by gkc** [comment]
Ack

**Comment by gkc** [comment]
@cpswan Closing; alerts have been resolved
