### ISSUE TITLE
Provide ability to use no-encrypt-traffic in srv

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/noports#1416]
### Is your feature request related to a problem? Please describe.

Sometimes users may not want to use encrypted sockets - perhaps for example they are using a protocol which already uses encryption. This always has to be used with appropriate user caution

### Describe the solution you'd like

Always encrypt by default; if user requests no encryption then show a prominent warning

**Comment by gkc** [comment]
Duplicate of #1417
