### ISSUE TITLE
universal.sh install issues macOS 15.01, M1 processor

### ISSUE THREAD

**Issue by kimdimick** [atsign-foundation/noports#1478]
### Describe the bug

chown errors or warning messages

### Steps to reproduce

1. First I ran the universal.sh script on a mac mini as root (sudo).
2. Then I selected device.
3. And then I answered the question.
4. When the script was completing the installation I saw chown errors and some warning  messages.

universial.sh script output.

=> Installed at_activate to /usr/local/bin
chown: kdimick: illegal group name
chown: kdimick: illegal group name
Warning: Expecting a LaunchDaemons path since the command was ran as root. Got LaunchAgents instead.
`launchctl bootout` is a recommended alternative.
Unload failed: 5: Input/output error
Try running `launchctl bootout` as root for richer errors.
Warning: Expecting a LaunchDaemons path since the command was ran as root. Got LaunchAgents instead.
`launchctl bootstrap` is a recommended alternative.
sshnpd installed with launchd

### Expected behavior

I didn't expect to see the chown message and the warnings messages.

**Comment by xavierchanth** [comment]
Macos shouldn't be run as root, will add a guard clause
