### ISSUE TITLE
Mac NoPorts UI menu bar menu enhancement 

### ISSUE THREAD

**Issue by kimdimick** [atsign-foundation/noports#1480]
### Is your feature request related to a problem? Please describe.

When I start the NoPorts UI the small menu in the menu bar displays "Loading" until I connect to one of the listed profiles. After a connection has completed the profiles display "On" or Off"

### Describe the solution you'd like

Maybe we could use "Ready" or "Off" and once the connection is established could we use"Connected" as a replacement for "On"?

Below is a screenshot displaying the NoPorts Dashboard and the menu bar menu.

![Screenshot 2024-10-31 at 2 43 41 PM](https://github.com/user-attachments/assets/6aa10e32-6b45-47fa-9c10-0b05a34740e4)

**Comment by xavierchanth** [comment]
This is already fixed on trunk
