### ISSUE TITLE
Wrong MAC OS Binary in #v1.1.0 Release

### ISSUE THREAD

**Issue by grifonas** [atsign-foundation/noports#15]
**Describe the bug**
`sshnp` binary is of `Mach-O 64-bit executable arm64` architecture in both `sshnp_OSX_arm_64.tar.gz` and `sshnp_OSX_x86_64.tar.gz` files. 

**To Reproduce**

1. Download both archives.
2. Extract both.
3. Run `file sshnp/sshnp`

**Expected behavior**
`sshnp_OSX_x86_64.tar.gz` should contain the correct `x86_64` architecture. 

**Screenshots**
Please see a short video demonstrating the issue attached. 
https://user-images.githubusercontent.com/1979797/172198065-84c93e75-72e9-4301-a17a-6389b29a68b0.mov

**Smartphone (please complete the following information):**
 - Device: MAC

 - OS: MAC OS

**Comment by cconstab** [comment]
Oops my bad !

Will fix soon !

**Comment by cconstab** [comment]
OK the right files uploaded !

If you get the pop up saying this code is unknown by Apple but you trust me and my tool chain (Dart.dev) then...

In Finder find the binary click and hold control then click the binary and then 'open' that will bypass the check and you can run the binary from the cli.

Let me know how you get on as I compiled this on an ARM M1 mac for X86..

Colin

**Comment by grifonas** [comment]
Thanks! The files are correct now. 👍 

I actually compiled it myself yesterday, so all good.

Still couldn't get it to work but that another issue. 
Will open one if I can't sort it out. 
Thank again!
