### ISSUE TITLE
Sshnp Installer Binaries

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#150]
# Full Installers List:
- [ ] `install_sshnpd`
- [ ] `install_sshnp`
- [ ] `install_sshrvd`

The main purpose of the installers is to

- create directories & files, if they dne
- generate custom `~/.startup.sh` script

## sshnp installer

Running `./install_sshnpd` would:

## sshnpd installer

Running `./install_sshnpd` would:

- Make dirs if dne (`~/.ssh/`, `~/sshnp/`, `~/.atsign/keys`) using `mkdir -p`
- `cp` everything that came with the tar and move it to ~/sshnp, ask to overwrite if it is already installed of course
- ~~move `sshnpd`/`tmux-sshnpd` to `/usr/local/at`~~ **EDIT: @cconstab i believe your advice was to not move the binaries to `/usr/local/at`.**
- create `healthcheck.sh` script and put it in ~/sshnp, checks for dirs and files installed
- read args (`-a`, `-m`, `-u`, etc.) then write a custom `.startup.sh` and put it in `/$USER`. `.startup.sh` will utilize `healthcheck.sh`
- ~~write custom `sshnpd.service` then tell person to type `sudo systemctl enable sshnpd.service` to enable~~ **EDIT striked as per @cconstab's advice**

Runing **.startup.sh** would:

- make directories (~/.atsign/keys, ~/sshnp, /run/sshd, and ~/.ssh)
- touch `~/.ssh/authorized_keys` and `chmod 600` if dne
- exit if daemon .atKeys dne
- exit if /usr/sbin/sshd not found
- run all this stuff:

```sh
ssh-keygen -A
/usr/sbin/sshd -D -o "ListenAddress 127.0.0.1" -o "PasswordAuthentication no"  &
$sshnpHomeDir/sshnpd -a ${argResults['atsign']} -m ${argResults['manager']} ${argResults['device'] != null ? '-d ${argResults['device']}' : ''} ${argResults['sshpublickey'] ? '-s' : ''} ${argResults['username'] ? '-u' : ''} ${argResults['verbose'] ? '-v' : ''}${argResults['keyFile'] != null ? '-k ${argResults['keyFile']}' : ''}
```

Then all you would have to do to start up the daemon would be to do `sh ~/.startup.sh`

## sshrvd installer

**Comment by cconstab** [comment]
Touch the authorized_keys file and chmod 600

**Comment by cconstab** [comment]
The service is not needed I woukd recommend just using the scripts as not root required
