### ISSUE TITLE
Onboarding Issues in NoPorts Desktop

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/noports#1520]
Fix the below issues in NPT Desktop:

- [ ] Get Started > Next (without entering an atSign) > Get a free atSign.. It takes you back to the start screen instead of an atSign generator.
- [ ] Get Started > Next (without entering an atSign) > Upload atKeys > Cancel .. The app disappears into the background
- [ ] Get Started > Next (without entering an atSign) > Upload atKeys > Upload corrupt or invalid keys > “Notice .. Auth Failed” on screen .
- [ ] Get Started > Next (without entering an atSign) > Activate atSign > Activate (without entering an atSign).. The app goes back to the previous screen instead of showing text saying the person should enter their atSign
- [ ] Get Started > Next (without entering an atSign) > Activate atSign > Enter a non-existent atSign and click Activate > “Notice.. Unauthorized” on screen
- [ ] Get Started > Enter an unactivated atSign and click Next > Activate atSigns > Enter atSign again and click Activate > It hangs on the “Fetching atSign Status” screen
- [ ] Get Started > Next (without entering an atSign).. It proceeds to the next screen. What’s the point of entering an atSign then? Similarly if you enter an atSign you want to activate, it still asks you to enter the atSign you want to activate two screens later.

**Comment by xavierchanth** [comment]
I already have a ticket in at_widgets for this
