### ISSUE TITLE
NoPorts Dashboard incorrect item deleted

### ISSUE THREAD

**Issue by kimdimick** [atsign-foundation/noports#1530]
### Describe the bug

I have multiple items listed in the dashboard and when I delete an item such as item number 2 the last item in the list is deleted.

### Steps to reproduce

1. First, ensure you have more than two items in the list of profiles.
2. Then, select an item other than the last item in the list. 
3. And then, use the menu under the 3 dots and select delete.
4. Note, the last item is deleted, not the item you selected and used delete from the menu. Also, note none of the boxes on the left were selected.

### Expected behavior

I expected the item I selected and used the delete from the menu for to be deleted.

### Screenshots

I have three screenshots. The first screenshot displays the list of my npt connection items, and the second screenshot displays item number 2 selected and the menu under the three dots. I choose delete and the third screenshot displays the last item being deleted.
![NoPorts-connection-list-before-delete](https://github.com/user-attachments/assets/47226f19-94e8-424d-91c1-45d9aec69b6b)

![NoPorts-Dashboard-item-2-selected-foe deletation](https://github.com/user-attachments/assets/5b683a41-af2f-45e1-b983-d969fa922eda)

![NoPorts-Dashboard-last-item-delete](https://github.com/user-attachments/assets/7c3373b3-aabc-4133-bef1-2bf2aab6a42c)

**Comment by CurtlyCritchlow** [comment]
Bug fixed in PR #1583
