### ISSUE TITLE
NoPorts Dashboard (MacOS) drops back on startup

### ISSUE THREAD

**Issue by kimdimick** [atsign-foundation/noports#1574]
### Describe the bug

NoPorts Dashboard (MacOS) drops behind other running clients/applications on startup. 

### Steps to reproduce

1. First I have Apple Mail and Safari running and open.
2. Then I start the NoPorts Dashboard from my dock
3. And then the NoPorts dashboard comes up and quickly moves behind the client or application that is running in the foreground.
4. I am attaching a short 8-second video of the issue.

### Expected behavior

I expected the NoPorts dashboard to stay in the foreground until I clicked "Get started" and entered or selected my at_sign.

### Screenshots

https://github.com/user-attachments/assets/af86b19f-c53d-4676-9797-703f0b9b04ae

**Comment by xavierchanth** [comment]
Fixed in 1.1.4
