### ISSUE TITLE
sysctl: permission denied on key "net.ipv4.ping_group_range"

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#168]
### Describe the bug

When building the sshnpd Docker image at the end of Step 12/15:

```
Adding group `atsign' (GID 1024) ...
Done.
sysctl: permission denied on key "net.ipv4.ping_group_range"
```

Because we don't (yet) `set -eux` at the start of the `RUN` block this doesn't cause the step to fail.

### Steps to reproduce

1. First I clone this repo
2. Then I `cd sshnoports`
3. And then `sudo docker build -t atsigncompany/sshnpd .`

### Expected behavior

The command should succeed, or the build should fail.

### Additional context

@JeremyTubongbanua found that the line works with `FROM ubuntu`, and that it's needed to run things in his demo container https://github.com/atsign-foundation/at_demos/pull/97

@cconstab I _think_ you put this in so that the daemon can be started as a non root user, and that it worked with an Ubuntu base image, and has been failing with Debian, which might explain `#USER atsign` being commented out

Could this be a build time problem that could be moved to `startup.sh`?

**Comment by cconstab** [comment]
closing with 
https://github.com/atsign-foundation/sshnoports/pull/222

**Comment by JeremyTubongbanua** [comment]
@cconstab There's a --sysctl flag in `docker run`

Not sure if that can be of any help here

https://docs.docker.com/engine/reference/commandline/run/#sysctl

<img width="754" alt="image" src="https://github.com/atsign-foundation/sshnoports/assets/79019866/214a87b3-ea82-440c-8d7b-9c465f9f4584">
