### ISSUE TITLE
SSHNPD Docker Image

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#185]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Docker image which accepts the arguments required to install sshnpd to a container.

- Doesn't need tmux / to run in the background
- Should be capable of being entirely configured via docker compose
  - For running on the docker host network

**Comment by xavierchanth** [comment]
I think this is already done [here](https://hub.docker.com/r/atsigncompany/sshnpd/tags), it just needs to be documented.

**Comment by xavierchanth** [comment]
@cpswan can you confirm what, if anything, needs to be done here?

**Comment by cpswan** [comment]
There is already a [Dockerfile](https://github.com/atsign-foundation/sshnoports/blob/trunk/Dockerfile) that builds the [atsigncompany/sshnpd](https://hub.docker.com/r/atsigncompany/sshnpd/tags) image and [automation](https://github.com/atsign-foundation/sshnoports/blob/trunk/.github/workflows/dockerhub_sshnpd.yml) to create new images when we tag releases.

The [documentation](https://github.com/atsign-foundation/sshnoports/tree/trunk#sshnpd-daemon-in-a-docker-container) is in the main README, and is minimal, but functional. So this ticket might be a no-op.
