### ISSUE TITLE
Carry over all flags from generated sshnp@<device>

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#186]
Not all flags in the generated binaries for sshnp and sshnpd work... we should make them configurable.

**Comment by gkc** [comment]
Which flags, Xavier?

**Comment by xavierchanth** [comment]
Not all of the flags from `sshnp` are available in the `sshnp@<device>` script. 
Not all of the flags from `sshnpd` are available in the `sshnpd@<client>` script.

What's needed is to ensure that all flags are passed through...

**Comment by JeremyTubongbanua** [comment]
So an example would be something like passing the `-v` flag is what this issue is about @XavierChanth ?

**Comment by xavierchanth** [comment]
exactly :)

**Comment by xavierchanth** [comment]
These files are the ones that don't support all of the flags of the original binaries.
https://github.com/atsign-foundation/sshnoports/blob/trunk/templates/client/sshnp-full.sh
https://github.com/atsign-foundation/sshnoports/blob/trunk/templates/headless/sshnpd.sh

**Comment by xavierchanth** [comment]
This may be replaced by #217

**Comment by xavierchanth** [comment]
sshnpd@<client> wrapper doesn't need to be replaced since it should all be automated anyways.

sshnp@<device> wrapper has a PR open to fix this
