### ISSUE TITLE
Sshnp not receiving Sshnpd deviceName until both atSigns activated

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#188]
### Describe the bug

The sshnpd tmux session continuously runs `sshnpd` and patiently waits for the `.atKeys` to be generated. If the device atSign is onboarded before the client atSign, then the deviceName is never shared with the client atSign, since the client atSign does not yet have a `public:publickey@`

If I am correct, the notification of the deviceName is being sent without caring if the client receives it or not. Then goes straight into `monitor`. Only once the client is setup, then the device's sshnpd has to be restarted

### Steps to reproduce

1. On device, run sshnpd installer
2. On device, run `./at_activate`
3. On device, tmux session successfully started sshnpd, :)
4. On client, run sshnp installer
5. On client, run `./at_activate`
6. On client: Could not receive the device name from sshnpd since sshnpd tried sharing the device name before sshnp's atsign could activate first

### Expected behavior

I guess it is working as intended (in that two non-onboarded atSigns are unable to communicate to one another), but if the goal of the do-while inside the tmux session was for it to start up the daemon, then it is not going as planned :(

`sshnp` recognize deviceName given by `sshnpd`

### Additional context

2 fixes:

1. (documentation fix): expect the person to *know* that both of the atSigns MUST be onboarded before running the `sshnpd` and `sshnp` binaries. maybe even avoid starting up the tmux session to let *them* start it themselves? tell them to specifically that client `sshnp` HAVE to be setup before device `sshnpd`

3. (software fix): ensure that the notifications are received and that the receiving-end is indeed an onboarded atSign, by doing `final NotificationResult notifResult = await notificationService.notify(...)` check for `    notificationResult.notificationStatusEnum == NotificationStatusEnum.delivered`

**Comment by xavierchanth** [comment]
- public key check as discussed in planning

**Comment by JeremyTubongbanua** [comment]
To expand on discussion:

The issue is that the notifications are being sent to the client atSign without checking if the client atSign is even onboarded.

The solution is to check for a public key on the client (aka manager) atSign.
Wait until it exists before it does the notification of the username.

**Comment by JeremyTubongbanua** [comment]
CC @cconstab @gkc
