### ISSUE TITLE
getsshnp and getsshnpd quick install flags

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#199]
### Describe the bug

Using the installer script with flags does not work for me.

### Steps to reproduce

1. Run the sshnp installer with client, device and region options `bash -c "$(curl -fsSL https://getsshnp.noports.com)" -c @alice_client -d @alice_device -h am`
2. I get `Unknown argument: @alice_client`

See **Screenshots**

### Expected behavior

Does not start the REPL, instantly starts installation

### Screenshots

```sh
jeremytubongbanua@Jeremys-M2-Air ~ % bash -c "$(curl -fsSL https://getsshnp.noports.com)" -c @alice_client -d @alice_device -h am
Unknown argument: @alice_client
```

### Smartphones

Got same error inside ubuntu arm64 docker container and Mac OS (m2 air zsh)

### Additional context

**UPDATED**

Xavier said I missed `--` which was also missing in the instructions

**Comment by JeremyTubongbanua** [comment]
CC @XavierChanth

**Comment by xavierchanth** [comment]
What OS / device is this @JeremyTubongbanua?

**Comment by JeremyTubongbanua** [comment]
> What OS / device is this @JeremyTubongbanua?

Tested it both on my Mac (M2 Air) and inside a Docker container (ubuntu arm64)
Same error for both

**Comment by xavierchanth** [comment]
NVM - you missed `--` 
```
~ took 31s 
➜ bash -c "$(curl -fsSL https://getsshnp.noports.com)" -- -c @xavierchanth
Device address (e.g. @alice_device): ^C
```

**Comment by xavierchanth** [comment]
I'll make sure the instructions are updated

**Comment by JeremyTubongbanua** [comment]
That worked!

```sh
atsign@97d938f6824a:~$ /bin/bash -c "$(curl -fsSL https://getsshnp.noports.com)" -- -c @thechosencancer -d @fantasticcoffee -h am        

Downloading sshnp from https://github.com/atsign-foundation/sshnoports/releases/download/v3.3.0/sshnp-linux-arm64.tgz
Installed binaries: sshnp at_activate sshrv update_sshnp
Installing sshnp@fantasticcoffee to /atsign/.local/bin/sshnp@fantasticcoffee

Added /atsign/.local/bin to your PATH.
Include the following line in your shell profile to persist across logins:
  export PATH="$PATH:/atsign/.local/bin"

Installation complete
```

**Comment by xavierchanth** [comment]
Fixed in the instructions, should be updated soon
