### ISSUE TITLE
sshnp: add -u option to specify username to use if sshnpd is not sharing it

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/noports#202]
### Is your feature request related to a problem? Please describe.

from @cconstab 
> sshnp shoukd have a -u option to specify the username if the sshnpd was not sharing it.
> This is a bug/oversight in sshnp right now.

### Describe the solution you'd like

* add an optional `-u` option in SSHNP.createArgParser with full option name `remote-user-name`, description something like, "user name to use in the ssh session on the remote host"
* in SSHNP, change `remoteUserName` from `late final String remoteUsername` to `String? remoteUserName`
* add optional `remoteUserName` parameter to SSHNP constructor to allow remoteUserName to be supplied, and supply the parsed 
* in SSHNP.init - do not call `fetchRemoteUserName` if a remoteUserName has already been supplied

### Additional context

Either wait for https://github.com/atsign-foundation/sshnoports/pull/201 to be merged to trunk, or make a new branch based on that PR's branch

**Comment by VJag** [comment]
@purnimavenkatasubbu Can you work on this ticket? @srieteja can help if you need.

**Comment by purnimavenkatasubbu** [comment]
PR merged to trunk. Closing this issue as fixed.
