### ISSUE TITLE
SSH No Ports: Kill a sshnpd process through a notification

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#235]
It is difficult to simply restart an sshnpd process for a particular device name if there are multiple instances running. 

It might be useful to implement a kill sshnpd command through a notification which would cause it to exit so that it can be restarted by the local restart service.

**Comment by cconstab** [comment]
nice idea

**Comment by xavierchanth** [comment]
Closing this issue, as we've deemed it a potential vulnerability
