### ISSUE TITLE
SSH No Ports: Periodic E2E "Sanity" Tests

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#252]
## What needs to be done

Periodic sanity tests (maybe once/twice a week via a cron schedule):

- [ ] TODO: Matrix of Release 3.1.2, Release 3.2.0, Release 3.3.0, Release (latest), and latest trunk
- [ ] Actually writing the tests in a github action

**Comment by xavierchanth** [comment]
Should be easy for me to uptake this work given the other stuff I am working on

**Comment by JeremyTubongbanua** [comment]
> Should be easy for me to uptake this work given the other stuff I am working on

Sounds good +1

**Comment by JeremyTubongbanua** [comment]
I know you're busy and I already had some work on this @XavierChanth, are you sure you don't want me to take this?

**Comment by xavierchanth** [comment]
> I know you're busy and I already had some work on this @XavierChanth, are you sure you don't want me to take this?

Sorry it was completed in #274 I forgot to close this ticket

Very easy for us to add more tests to the matrix if we need them now
