### ISSUE TITLE
Race condition in sshnpd if starting multiple sshnp clients simultaneously

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/noports#277]
### Describe the bug

`_privateKey` is an instance variable of SSHNPDImpl. It is set when sshnpd receives a `privatekey` notification from sshnp, and is later used when sshnpd receives a `sshd` notiication from sshnp.

If there are two sshnp clients connecting to the same sshnpd at approximately the same time, then it is possible for the following to happen
- client 1 sends privatekey
- client 2 sends privatekey
- client1 sends sshd --> sshnpd will use privatekey sent by client2 when creating the ssh socket

The race condition is rarely likely to occur in real world usage, but should be fixed anyway. However - see "Additional context" section below for why we may not wish to fix this problem. Assigning Type of 'Discussion' so we can discuss on an architecture call.

### Steps to reproduce

Haven't yet built a test harness to reproduce, found while doing a code walkthrough

### Expected behavior

This race condition should be prevented.

The sshnp client sends its sessionId when it sends the `sshd` notification. One way of solving the problem would be
- also send the client's session ID as part of the `privatekey` notification in either the key or the value of the notification.
- sshnpd could then store the privatekeys it receives in a map keyed by the client's sessionId.
- However this would break backwards compatibility, since sshnpd v3.3.0 and earlier expect the value of the notification to be just the private key, and expect the `key` of the notification to be `privatekey.$device.sshnp`

#### Fix proposal
- Once we have the ability for sshnp to find out the version of the sshnpd it is connecting to, then we can implement the behaviour above when sshnpd is at a version which supports it. I suggest the best approach is to make the value of the notifications be serialized JSON objects rather than simple Strings - e.g. `{"privateKey":"$privateKey","sessionId":"$sessionId"}`
- sshnpd can then check the value of the `privatekey` notification and if it is JSON, it can deserialize it and then get the privateKey and the sessionId, or if it is still just a String (from an older sshnp client) then it can just get the privateKey

### Additional context

Note that this race condition will not exist when we support direct ssh via rvd rather than a reverse ssh, since sshnpd will only be adding to its authorized_keys file the ephemeral publickey it receives from sshnp

**Comment by xavierchanth** [comment]
Is this something that was fixed when you wrote fwd ssh @gkc ?

**Comment by gkc** [comment]
> Is this something that was fixed when you wrote fwd ssh @gkc ?

Yes @XavierChanth this is no longer an issue in v4+
