### ISSUE TITLE
Check for ssh daemon during install

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#291]
### Is your feature request related to a problem? Please describe.

The first line of our [Installation Guide](https://www.noports.com/sshnoports-installation#FAQ) reads (my emphasis):

> Before you begin, you'll need to set up curl and sshd on **both your client and your remote device**.

Yet we're painfully aware that people don't set up sshd, particularly on the client, which is why item 1 of the Installation FAQ is:

> 1. How do I resolve an SSHAuthAbortError (connection closed before authentication)?
>
> Generally, this error is caused because sshd is not running on one of the machines. SSH No Ports requires sshd to be enabled for localhost connections on both devices. To test whether the device is running sshd on localhost, run the following command on the device:

### Describe the solution you'd like

Test for the presence of an ssh daemon during install and warn if it's not found

### Describe alternatives you've considered

We could also test at runtime from sshnp and sshnpd and warn.

We could offer to install sshd if it's not found at installation (and even configure to just listen on localhost and maybe not bind to 22).

**Comment by xavierchanth** [comment]
I (half) check for this in the current script, but there are improvements to be made. Reducing to 2 SP.

**Comment by xavierchanth** [comment]
I had added a check for this but it is unreliable, and not worth the amount of effort it will consume for me to perfect it... backlogging until it becomes more important

**Comment by xavierchanth** [comment]
See #327 which I think is more important, easier to implement, and will cover for this

**Comment by xavierchanth** [comment]
Moved #327 to P1, and this to P3

**Comment by xavierchanth** [comment]
This installer is deprecated, closing
