### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#3]
**Describe the solution you'd like**
Add binaries for Windows, along with some guidance on installing a suitable SSH server.

**Comment by cconstab** [comment]
Will do as soon as I have openssh running as it should on windows. It has a bunch of shall we say quirks.

The main one I have found so far is ignoring public keys !

**Comment by cconstab** [comment]
Windows ignores ssh keys if your account has administrator rites.. Which means that to use sshnoports its best to set up a new account with no admin rites.. It is now stumbling but more documentation needed the sshnp code is now working.

**Comment by cconstab** [comment]
v3.1.2 work just fine under WSL2 if using a rendezvous point now! Windows it self  is still too messy !

**Comment by cpswan** [comment]
Might it make sense to just have the `sshnp` client on Windows? Particularly for use in Cygwin/Git Bash?

Though I'd expect that most of the people who used to use those things have jumped to WSL2 now.

**Comment by cconstab** [comment]
Now we have the rendezvous server we no longer have to have sshd running on the client and so we have started working on a client for Windows/Mac/Linux that offers a GUI to connect to remote devices and allow ssh clients to connect to a local port and be tunneled to the remote device.

https://github.com/atsign-foundation/sshnoports/issues/163

Details that progress so this issue will be closed
