### ISSUE TITLE
Does .vscode directory need to be in this repo (or should it be .gitignore

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#311]
### Describe the bug

#285 introduced .vscode/launch.json but it probably shouldn't be here

### Steps to reproduce

NA

### Expected behavior

Less clutter

**Comment by xavierchanth** [comment]
The launch.json is intended, it is generic and should work on any system using that system's preferred python installation.

**Comment by cpswan** [comment]
@XavierChanth can we maybe add some commentary to it to explain why it's there then?

**Comment by xavierchanth** [comment]
I don't see it as necessary, it's default launch.json config that vscode automatically creates for you. The name of the launch config as it appears in vscode is "Python: Current File" and it does exactly what you would expect, it runs the currently open python file.

![CleanShot 2023-08-09 at 17 28 38](https://github.com/atsign-foundation/sshnoports/assets/33691921/f8082f23-ca74-4297-a254-0e497aea526b)
