### ISSUE TITLE
sshnpd should check if sshd is running

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#327]
### Describe the bug

I was doing some installation testing for the sshnpd installer and I had left sshd disabled on my test environment. This morning I could not figure out why sshnp was seemingly hanging forever when trying to connect.

sshnpd contain only this message as an indication to the issue:
```
INFO|2023-08-11 05:11:50.775191|SyncService (@xchan)|230038671|Returning serverCommitId 2143 

SEVERE|2023-08-11 05:11:52.669250| sshnpd |SSH Client failure : SocketException: Connection failed (OS Error: Cannot assign requested address, errno = 99), address = localhost, port = 22 

INFO|2023-08-11 05:11:53.551336| sshnpd |SUCCESS:id: ab649191-85e6-430c-a1a6-56d1e89f8bd8 status: NotificationStatusEnum.delivered for: cab6ca9b-a575-4b5f-8c7e-d5c7f7952ff9 
```

### Steps to reproduce

Turn off sshd where sshnpd is running. Try to connect via sshnp

### Expected behavior

Ideally sshnpd checks if ssh is running and returns an error to the client.

**Comment by xavierchanth** [comment]
@gkc @cconstab you may have some thoughts about this

**Comment by cpswan** [comment]
Good call @XavierChanth I've been talking to @gkc over the past week about the need for us to check that key dependencies are present. But we should also be checking that they're up, as from a UX point of view we're to blame until proven otherwise.

Taking things a step further... should we have a means to (re)start sshd if it's not in a state to receive connections?

**Comment by xavierchanth** [comment]
I started with making sure they are installed for the installer, but I also need it to check that sshd and cron are running (which is a bit trickier)

**Comment by xavierchanth** [comment]
But we definitely need to make sure sshd is running from sshnpd itself, because we just assume, and it causes sshnp to hang, and with little to no explanation on either client or device.

**Comment by xavierchanth** [comment]
I have a few ideas for how we implement this, and what should happen if sshd is down, and I'm not sure which is the correct answer...

How to implement the check:
- make an ephemeral key pair
- store the ephemeral public key in authorized keys
- try to ssh connect to localhost (probably using pure dart)
- wait for client to connect and authenticate, then confirm that it is

Where to implement the check:
- At startup of sshnpd
- periodically
- with each sshd request (not a fan, would impact overall performance)

What should happen if the check fails:
- Warning in stdout / stderr (always)
- Should sshnpd exit? ~maybe for the dockerhub version
  - We could add a behavioural flag that determines what happens
    `--on-sshd-failure` with options [warn, error]
- Should it store the sshd status and warn/error the sshd request on a failed connection?

**Comment by cpswan** [comment]
@XavierChanth some further thoughts based on your last comment...

* do we have to test the happy path to verify that sshd is running. It might be much quicker/easier to run a test that we know will cause an error, but sometimes a quick error is better than a slow wait for nothing to happen (and may also be better than a journey all the way down the happy path).
* at startup seems like a no brainer
* agree that at each sshd request is likely to be too much of an overhead
  * but maybe monitor those requests, and if they time out *then* test that sshd is responding
* I don't think sshnpd should exit, but also logs etc. on that host aren't much help if you can't get onto it with ssh
  * so it needs to be able to notify the sshnp client that there's a problem with sshd (and what it's attempting to do to resolve that)

**Comment by xavierchanth** [comment]
> @XavierChanth some further thoughts based on your last comment...
> 
> * do we have to test the happy path to verify that sshd is running. It might be much quicker/easier to run a test that we know will cause an error, but sometimes a quick error is better than a slow wait for nothing to happen (and may also be better than a journey all the way down the happy path).
> * at startup seems like a no brainer
> * agree that at each sshd request is likely to be too much of an overhead
>   
>   * but maybe monitor those requests, and if they time out _then_ test that sshd is responding
> * I don't think sshnpd should exit, but also logs etc. on that host aren't much help if you can't get onto it with ssh
>   
>   * so it needs to be able to notify the sshnp client that there's a problem with sshd (and what it's attempting to do to resolve that)

We may also want to check that sshd is running on the client when doing reverse ssh

**Comment by cpswan** [comment]
> We may also want to check that sshd is running on the client when doing reverse ssh

Agreed, and the mechanism we use for sshnpd can likely be reused for sshnp

**Comment by xavierchanth** [comment]
We can revisit this ticket after the 4.0.0 launch

**Comment by xavierchanth** [comment]
We have this built into the systemd installation script, which I think is good enough for most situations.
