### ISSUE TITLE
Access string printed to stdout when ssh is successful or successful in a flutter environment.

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/noports#360]
### Is your feature request related to a problem? Please describe.

I can use sshnoports to ssh into a remote device from a GUI app but I cannot access the string printed to stdout when ssh is successful to display in the GUI app.

### Describe the solution you'd like

I would like to have access to the string printed to stdout when ssh is successful or unsuccessful to display in the GUI app.

**Comment by gkc** [comment]
@XavierChanth is this something you can pick up today? I'm going to be unexpectedly away from keyboard for most of Friday

**Comment by xavierchanth** [comment]
Will do

**Comment by xavierchanth** [comment]
#367

**Comment by gkc** [comment]
@CurtlyCritchlow Xavier has implemented the necessary changes and the PR has been merged to trunk. If/when it's working for you, please close this ticket.

**Comment by xavierchanth** [comment]
> @CurtlyCritchlow Xavier has implemented the necessary changes and the PR has been merged to trunk. If/when it's working for you, please close this ticket.

SSHNP.run now returns a SSHNPResult with a subclass of either SSHCommand or SSHNPFailed, SSHCommand contains a .toString() override with the full ssh command, or you can pick out the bits and pieces needed to run in pure dart (which I will be working on soon)
