### ISSUE TITLE
Fix list-devices error message version

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#374]
![image](https://github.com/atsign-foundation/sshnoports/assets/33691921/833c4fec-603a-4b8a-8d8e-24ddab7b75e8)
v3.5.0 -> v3.4.0 in the error message above

**Comment by xavierchanth** [comment]
I will have to add a commit off of the v3.4.0 tag, then rebuild, publish v3.4.1, and then will submit a PR to merge to trunk.

**Comment by JeremyTubongbanua** [comment]
CLose @XavierChanth ?
