### ISSUE TITLE
Cron job eventually stops attempting to start daemon

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#379]
### Describe the bug

Cron job attempts to start daemon a couple of times then stops trying

Everything works with tmux, I've noticed.

Video of me reproducing it: https://drive.google.com/file/d/1MGnbwQyWfm8LEkFjvcq1rLXEqbi3x4M0/view?usp=sharing

### Steps to reproduce

1. On your device, run the SSHNPD installer script
2. Since I don't have tmux, it will resort to cron and logrotate
3. I tail -f ~/.sshnpd/logs/@jeremy_0.log
4. it stops trying attempting to run sshnpd eventually, even when I provide it some keys

### Expected behavior

Keep on attempting

### Additional context

There was a while loop for checking if the sshnp device exists in #211 , but is not in the SSHNPD code anymore

**Comment by JeremyTubongbanua** [comment]
I don't think the daemon should be started up on its own

When I install something like a video game, I don't expect it to open immediately.

**Comment by xavierchanth** [comment]
> I don't think the daemon should be started up on its own
> 
> When I install something like a video game, I don't expect it to open immediately.

Make a separate discussion ticket for this please.
Edit: made one here https://github.com/atsign-foundation/operations/issues/79



Can you check that nohup is available in your environment `command -v nohup`

**Comment by xavierchanth** [comment]
@JeremyTubongbanua if this is in Docker then cron won't start the daemon at all because cron is not started when the container is started, and I use the reboot notation. This needs to be tested on an actual vm / device first

**Comment by JeremyTubongbanua** [comment]
Putting this as P1 since this bug would mean the installation instructions don't work on Docker containers

**Comment by xavierchanth** [comment]
They don't need to work on docker containers, but there was a missing check in the installer which might cause it to fail. The CRON solution requires both logrotate and nohup to be installed
