### ISSUE TITLE
The -o option does not put in a space and so fails to work (v 3.4.1)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#391]
### Describe the bug

When using the -o there is not a space put in the command that is run (you can put in a manual space as a work around for the moment)

e.g.

```
cconstab@tarial ~ % sshnp -f @cconstab -t @kryz_9850 -d xmtpi -h @rv_am -s id_ed25519.pub -o "-L 9000:192.168.10.1:80" 
ssh -p 50687 pi@localhost -o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes -i /Users/cconstab/.ssh/id_ed25519-L 9000:192.168.10.1:80 
```

Notice the '/Users/cconstab/.ssh/id_ed25519-L 9000:192.168.10.1:80 ` lack of space !

### Steps to reproduce

1. First run the command 
2. Then I see the error
3. And then manually put in the required space and things work

### Expected behavior

No need for the space in the '-o' option

### Smartphones

- sshnp 3.4.1

**Comment by xavierchanth** [comment]
I'll put up a PR to release a v3.4.2 with this fix...

I believe the behaviour of this option is broken on trunk due to my misunderstanding of the feature

**Comment by xavierchanth** [comment]
Actually, I won't create a PR because we don't want to merge this to trunk since it has already changed drastically... I will create a pre-release which can be approved and released as latest

**Comment by xavierchanth** [comment]
Doing a multibuild to add to the release before we promote:

https://github.com/atsign-foundation/sshnoports/actions/runs/5998264887

**Comment by xavierchanth** [comment]
The other part of this issue is fixing the behaviour on trunk, which I will add to a PR
