### ISSUE TITLE
v3.2.0 ssh timeouts

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#392]
The v3.2.0 backward tests stopped working, and I thought it was simply timeouts caused by the GH actions runners taking too long. However, that is not the case... 

After consistent fails with the following 3 tests, I've decided to pursue further testing:
<img width="267" alt="CleanShot 2023-08-28 at 17 10 42@2x" src="https://github.com/atsign-foundation/sshnoports/assets/33691921/c8242ce2-fc0d-4859-acd9-1e162efa6e6e">

I will add to this ticket as more investigations take place

**Comment by xavierchanth** [comment]
I tested v3.2.0 against itself just to be certain that it still works.

**Comment by JeremyTubongbanua** [comment]
@XavierChanth doesn't the health check for container-sshnpd fix this ticket?

**Comment by xavierchanth** [comment]
No I think the tests are failing because the logs file becomes too large for the healthcheck or something... maybe extending the timeout will help

**Comment by xavierchanth** [comment]
Only a problem with <= 3.3.0 daemons

**Comment by xavierchanth** [comment]
I manually confirmed that these versions of sshnpd are backwards compatible last sprint.

**Comment by JeremyTubongbanua** [comment]
I think it would be worth to just drop v3.2.0 in our end-to-end backwards tests...

It's causing too much of a headache than it's worth and just deprecating the version I believe is easiest.

**Comment by gkc** [comment]
+1 to that, @JeremyTubongbanua

**Comment by xavierchanth** [comment]
We can leave as is then, those tests do not run unless we explicitly call them.
