### ISSUE TITLE
Document how binaries are created

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#4]
**Describe the solution you'd like**
Add a section to CONTRIBUTING.md showing how to compile the binaries.

**Describe alternatives you've considered**
Provide a GitHub Actions workflow that automates the binary creation process for new releases.

**Comment by cconstab** [comment]
Binaries for OSX might be tricky.. But yes to the others!

**Comment by cpswan** [comment]
#134 now provides a GitHub Action to build binaries for everything except macos/arm64

The steps to sign macOS binaries still need to be documented. @cconstab can we get a quick'n'dirty answer here with a chunk of your shell `history`?

**Comment by cconstab** [comment]
https://docs.google.com/document/d/1j0oGdWWSkpceiyWbBQRX9vOborW2V5_-SUg9f0EXa5U/edit?usp=sharing

**Comment by cpswan** [comment]
Thanks @cconstab 

The scripts I created seem to pretty much replicate what you originally commented above (before it was stomped by the GDocs link).

I'll do some more research on how feasible it is to automate the signing process.
