### ISSUE TITLE
3.4.2 reports as 3.4.1

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#411]
### Describe the bug

Version 3.4.2 of sshnp/sshnpd when run report as being 3.4.1

### Steps to reproduce

1. download 3.4.2 and run 

### Expected behavior

report the correct version umber

### Smartphones

Linux Arm64

**Comment by xavierchanth** [comment]
I updated the version # and retagged... I'm doing a rebuild of v3.4.2

**Comment by cconstab** [comment]
Thank you

**Comment by xavierchanth** [comment]
Rebuild has been uploaded, the only change to the code was the version string, and the version in pubspec.yaml (which has no impact on the code)

**Comment by xavierchanth** [comment]
I've also created #413 to avoid this kind of issue from happening in the future
