### ISSUE TITLE
Update GUI to show relevant `SSHNPParams` properties

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/noports#419]
### Is your feature request related to a problem? Please describe.

1. Currently the Home Screen shows more `SSHNPParams` properties that is needed
2. Currently the Connection Screen shows more `SSHNPParams` properties that the user does not need to edit.
3. the `SSHNPPartialParams` doesn't have default SSHNP properties set.

### Describe the solution you'd like

1. Show only `SSHNPParams` properties relevant for the Home Screen
2. Only show `SSHNPParams` properties that the user need to edit and rename field name to a more UI friendly name
3. Set the appropriate `SSHNPPartialParams`  properties to default SSHNP properties set.

**Comment by xavierchanth** [comment]
Closed by #424
