### ISSUE TITLE
Alternate port tests fail on Dependabot PRs

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#454]
### Describe the bug

Dependabot PRs don't have access to secrets, which are needed by e2e tests, so the `e2e_alternate_port_test` job always fails on Dependabot PRs

### Steps to reproduce

1. First Dependabot finds a dependency to update.
2. Then Dependabot raises a PR
3. And then the pull_request:branches:trunk condition is satisfied for the end2end_tests workflow
4. The e2e_alternate_port_test job starts because `if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}` is satisfied (even though this condition pretty much duplicates the workflow conditions)
5. The tests fail because the runner has no access to secrets and thus can't use any atSigns

### Expected behavior

Tests should be suppressed for Dependabot PRs (as the others in the workflow are):

```
    # Don't run on forks (cause no secrets), don't run if dependebot (cause no secrets)
    if: ${{ github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]'}}
```

**Comment by JeremyTubongbanua** [comment]
Sorry @cpswan !

PR for this is in #462 awaiting for your approval and merge
