### ISSUE TITLE
Raspberry Pi 400 - sshnpd v3.4.2 not working // v3.3.0 works

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/noports#476]
### Describe the bug

When attempting to connect to Raspberry Pi 400 from client machine (MacOS {also tried Windows 10}), version 3.4.2 cannot establish a connection with the Pi 400. 

When down grading to version 3.3.0, a connection was successfully established. 

### Steps to reproduce

1. First I Install v3.4.2 sshnpd on Raspberry Pi 400
2. Then run v3.4.2 sshnp on MacOS
3. And then error occurs: `Remote sshnpd error: Failed to establish connection - exit code 255 (use --local-port to specify unused port)`
4. Terminate sshnpd tmux session on Pi 400
5. Run installer, specified version with --version v3.3.0 on Pi 400
6. Then run v3.4.2 sshnp on MacOS
7. Connection established

### Expected behavior

v3.4.2 sshnpd establishes connection

### Screenshots

<img width="926" alt="Screenshot 2023-09-14 at 3 57 43 PM" src="https://github.com/atsign-foundation/sshnoports/assets/66637408/1c0f21ed-fa83-42da-a1ea-e397a7ca83fa">

Above, connection was attempted on v3.4.2 on Pi 400. Connection that succeeded was v3.3.0

**Comment by xavierchanth** [comment]
@TylerTrott I'm not able to reproduce this issue, can you try reinstalling v3.4.2 to the pi, if that doesn't work I can debug with you further.


FYI Windows is not a supported client until (at least) v4.

**Comment by TylerTrott** [comment]
I will try reinstalling to the pi today. What image of Pi do you have on the 400? I imaged mine with x64 Raspberry Pi OS Desktop. I will ping you if it does not work still.

With the above issue and screenshot, I was using MacOS as the client.

**Comment by xavierchanth** [comment]
> I will try reinstalling to the pi today. What image of Pi do you have on the 400? I imaged mine with x64 Raspberry Pi OS Desktop. I will ping you if it does not work still.
> 
> With the above issue and screenshot, I was using MacOS as the client.

I don't have a Pi 400, the client should be fine... it may have to do with your Pi installation. You can try pulling the repo and using the -r flag built into the installer (need dart to be installed for this)

**Comment by gkc** [comment]
@TylerTrott is this still an issue?

**Comment by gkc** [comment]
@TylerTrott is this still an issue?

**Comment by TylerTrott** [comment]
Just tried it on version 3.4.2 and it now works with no problem for both client and Raspberry Pi.

**Comment by JeremyTubongbanua** [comment]
I bore witness :) +1

**Comment by xavierchanth** [comment]
> Just tried it on version 3.4.2 and it now works with no problem for both client and Raspberry Pi.

Yay! Whatever happened that other time must of been some weirdness related to you running the beta version of the installer.

**Comment by TylerTrott** [comment]
> > Just tried it on version 3.4.2 and it now works with no problem for both client and Raspberry Pi.
> 
> Yay! Whatever happened that other time must of been some weirdness related to you running the beta version of the installer.

Maybe, it could have potentially just been user error. I may have set something up incorrectly or had a small typo
