### ISSUE TITLE
feat: better error message when disconnected from the internet

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#483]
### Is your feature request related to a problem? Please describe.

This is the error you get if you run sshnp and the machine has no Internet

```
cconstab@tarial ~ % $(sshnp -f @cconstab -t @ssh_1 -d raksign1  -h @rv_am)     

Exception: Unable to authenticate. Please provide a valid keys file
Unhandled exception:
Exception: Unable to authenticate. Please provide a valid keys file
#0      AtOnboardingServiceImpl.authenticate (package:at_onboarding_cli/src/onboard/at_onboarding_service_impl.dart:323)
<asynchronous suspension>
#1      createAtClientCli (package:sshnoports/common/create_at_client_cli.dart:41)
<asynchronous suspension>
#2      SSHNPImpl.fromParams (package:sshnoports/sshnp/sshnp_impl.dart:230)
<asynchronous suspension>
#3      main (file:///Users/chant/src/af/sshnoports/packages/sshnoports/bin/sshnp.dart:27)
<asynchronous suspension>
zsh: command not found: Version
cconstab@tarial ~ % 
```

### Describe the solution you'd like

Much nicer just to check/or catch this error and let the person runing it know that likely there is no Internet available

### Describe alternatives you've considered

none

**Comment by JeremyTubongbanua** [comment]
@cconstab I believe the approach here would be to check a connection to the rootDomain and display a message like:

"Could not connect to root.atsign.org:64. Are you connected to the Internet?"

**Comment by xavierchanth** [comment]
This should really be implemented into at_onboarding_cli

**Comment by xavierchanth** [comment]
@srieteja can you take a look at this ticket please

**Comment by xavierchanth** [comment]
Arch call Nov 22:
Seems like we need to go further down the stack and throw better error messages depending on what fails. (Somewhere in at_auth or at_lookup)

**Comment by srieteja** [comment]
Updated exception handling in at_auth. There is some more work required in onbaording_cli. For that reason carrying it forward to PR76.
