### ISSUE TITLE
sshnp v3.4.2 has lost the '-P' option!

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#504]
### Describe the bug

-P was in 3.4.0 and is now gone ??

### Steps to reproduce

1. run with -P !

### Expected behavior

Specifies the local port number of sshd

### Additional context

```
cconstab@cally:~$ $(sshnp -f @cconstab -t @ssh_1 -h @rv_am -d dragino -P 22)
FormatException: Could not find an option or flag "-P".
cconstab@cally:~$
```

**Comment by xavierchanth** [comment]
-P was never in version 3.x.x

![CleanShot 2023-09-27 at 07 12 26@2x](https://github.com/atsign-foundation/sshnoports/assets/33691921/cb786eb4-d9e8-460b-ab0a-4262f237742e)

The earliest tags of it are v4.0.0+

**Comment by xavierchanth** [comment]
![CleanShot 2023-09-27 at 07 17 55@2x](https://github.com/atsign-foundation/sshnoports/assets/33691921/b55c3c97-47e0-4024-94fe-91c6da909596)
v3.4.0

**Comment by cconstab** [comment]
Interesting! It was pushed must have got crushed with another PR at some point
