### ISSUE TITLE
--list-devices sometimes shows things as Inactive when they are active

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#510]
### Describe the bug

Sometimes I see an inactive device that is active...

```
cconstab@tarial keys % sshnp -f @kryz_client -t @kryz_device -h @rv_am --list-devices
Searching for devices...
Active Devices:
  kryz_01 - v3.4.2
Inactive Devices:
  xmt_pi - v3.4.2
cconstab@tarial keys % sshnp -f @kryz_client -t @kryz_device -h @rv_am --list-devices
Searching for devices...
Active Devices:
  kryz_01 - v3.4.2
  xmt_pi - v3.4.2
Inactive Devices:
  [X] No devices found
cconstab@tarial keys % 
```

### Steps to reproduce

1. Just run sshnp --list-devices 

### Expected behavior

Show active devices as active - Is this a race issue ?

### Smartphones

- Linux

### Were you using an atApplication when the bug was found?

sshnp

**Comment by xavierchanth** [comment]
Looks like there was a timeout, the way list devices determines whether a device is active or not:

1. Client reads atKeys to get all potentially available devices names
2. Client sends a notification to ping each device
3. Client waits 5 seconds for devices to respond
4. Client creates lists of devices that did (active) and didn't (inactive) respond

**Comment by xavierchanth** [comment]
We could also go with the approach of checking whether the key is longer than 1 hour old (since it is designed to refresh every hour) but I would rather not, since it could report devices as active when they are not. I would much rather have devices report as inactive when they are, than active when they aren't.

**Comment by xavierchanth** [comment]
@cconstab Should I instead have: 

Active, Not responding, AND Inactive by implementing both strategies?

**Comment by cconstab** [comment]
My guess is 5 secs is not quiet long enough for a sleepy Pi to spin up and get the notification back.

It seems to work once awake just fine. Remember it needs to do a lot of work to get a notication out if all the connections have timed out..

Perhaps double the timeout first ?

**Comment by xavierchanth** [comment]
> Perhaps double the timeout first ?

Added in one of my PRs
