### ISSUE TITLE
Move parameters from SDK to CLI

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#573]
From a conversation with @gkc:
- Move `--legacy-daemon`, `--ssh-client` from noports_core to sshnoports package
- Extends the noports_core parser in sshnoports with the additional parsing

**Comment by gkc** [comment]
@XavierChanth Shall I pick this one up?

**Comment by xavierchanth** [comment]
> @XavierChanth Shall I pick this one up?

If you can, that would be great!

**Comment by gkc** [comment]
@XavierChanth I'll do this one tomorrow morning. I'm still thinking about https://github.com/atsign-foundation/sshnoports/issues/572#issuecomment-1824407496

**Comment by gkc** [comment]
@XavierChanth I've been twisting myself into knots trying to do this; dealing with the ArgParser and the args list and extending the arg parser in sshnoports package is straightforward enough, but removing those two args from SshnpParams has a large ripple effect. I'm not sure this is worth the effort ...

**Comment by xavierchanth** [comment]
I'll see if I can take a stab at this
