### ISSUE TITLE
Inaccurate Error Message for Already Activated atSign

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/noports#576]
### Describe the bug

Currently, the software displays an error message indicating activation failure due to an "Invalid data provided by user" and "... is an invalid atSign" when attempting to activate an atSign that is already registered and activated. This error message can be misleading in the scenario where a user is not sure if their atSign is already activated or not. 

When I use cmd `echo $?`, 0 is outputted. 

### Steps to reproduce

On client terminal:
1. `bash -c "$(curl -fsSL https://getsshnp.noports.com)"`
2. Entered client address (already activated address) 
3. Entered device address (also already activated)
4. Entered 'am'
5. `export PATH="$HOME/.local/bin:$PATH";`
6. at_activate -a @client_address_key (already activated key)

### Expected behavior

The software should recognize when an atSign is already activated and provide a specific error message indicating that the atSign is already registered, rather than displaying a generic "Invalid data provided by user" message.

### Screenshots

<img width="568" alt="Screenshot 2023-11-17 at 10 35 47 AM" src="https://github.com/atsign-foundation/sshnoports/assets/66637408/90986fe1-f04a-4675-a63a-1d2aaa11482a">

**Comment by xavierchanth** [comment]
If an atSign is already activated, we currently rely on this program returning a zero exit-code so that we know that the atSign is activated after the run. Useful for docker orchestration with an activate container.

**Comment by srieteja** [comment]
@TylerTrott from the screenshot in the issue description, I see one issue. It's possible that '@wildgreen_client_key' is not a valid atsign. at_activate only requires the atsign. Alternatively, you can provide your cram key with '-c' if you have access to one.

**Comment by xavierchanth** [comment]
> @TylerTrott from the screenshot in the issue description, I see one issue. It's possible that '@wildgreen_client_key' is not a valid atsign. at_activate only requires the atsign. Alternatively, you can provide your cram key with '-c' if you have access to one.

Good catch @srieteja, I think the atSign is `@wildgreen_client`

**Comment by srieteja** [comment]
I just checked with the root server and you are right @XavierChanth
