### ISSUE TITLE
Breaking Changes for SSH No Ports v5.0.0

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#609]
Placeholder ticket to capture breaking changes that need to be made for version 5.0.0
```[tasklist]
### Tasks
- [x] Rename sshrvd to srd and sshrv to sr
- [x] Single process client with Process.run( 'ssh', ... ) and pipes to stdout/stderr
```

**Comment by xavierchanth** [comment]
@gkc in v5, maybe we should try to eliminate the $( sshnp ... ) syntax, instead having sshnp call the ssh command using Process.run, and stream it to stdout / stderr? That way we can run sshrv internally, rather than needing a separate sshrv process.

**Comment by gkc** [comment]
Yes, I think that would be a very good idea.

**Comment by xavierchanth** [comment]
v5 is released, closing this
