### ISSUE TITLE
Implement encryption between client and the device

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/noports#626]
### Is your feature request related to a problem? Please describe.

- rvd's facilitates processes running on separated networks to establish a socket connection between them, via ports which the rvd assigns and then listens on
- processes connecting to the ports should be able to encrypt and decrypt the data the way they wish it to be

### Describe the solution you'd like

- When requested, rvd opens two ports, let's say PortA and PortB for a given session
- Client connecting to PortA makes the information related to PortB available to the other side (Device)
- Client creates a symmetric encryption key and shares this information with the device
- Now information shared between client and the device will be encrypted and decrypted using the symmetric key

**Comment by xavierchanth** [comment]
moving this to p1

**Comment by gkc** [comment]
Work is complete; socket_connector unit tests are complete; sshnoports unit tests are WIP; PRs need to be finalized and merged. 2 SP remaining for this and 2 SP for #519 which is addressed by the same PRs

**Comment by gkc** [comment]
Reducing to 1SP for final PR merge once e2e test overhaul has been completed as part of #659
