### ISSUE TITLE
When --legacy-daemon is true, ephemeral local port is not working, requiring -l to be set as well.

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#671]
### Describe the bug

When using a sshnpd at version 3.4.2 I cannot use the sshnp v4.x and using the --legacy-daemon option and get a connection.

### Steps to reproduce

1. First I set up a version 3.4.2 sshnpd service
2. Then I try and connect using a 4.x.x version of sshnp using the '--legacy-daemon' option
3. This fails with sshnpd not responding or in earlier versions of 4.x.x. with a port of 0 being using as the local ssh port (sshrv)
4. But using at 3.4.2 sshnp client works just fine

### Expected behavior

sshnp using the option should work and connect allowing people to upgrade the daemon to 4.x.x codebase..

### Screenshots

here is an asciicinema of the issue I have

https://asciinema.org/a/uYaLQLhkJY0D6l2VOTYmSHw7C

Linux x86

### Were you using an atApplication when the bug was found?

sshnp

**Comment by cconstab** [comment]
sshnp v4.0.0-rc8 works but only if the `-l` option is given so code worked at some point .. See below

 https://asciinema.org/a/k0JMt4eAsCjlAARQFXK51QEq6

**Comment by cconstab** [comment]
v4.0.1 works as well but also has the -l bug

**Comment by cconstab** [comment]
v4.0.3 also works but also has a bug with needing the -l option.. So this is broken in two ways at v4.0.4, this legacy does not work and the -l option needs fixing too..

Colin

**Comment by xavierchanth** [comment]
# Summary of issues

## Unsigned client regression

So it looks like the unsigned / legacy client implementation has a regression. We no longer try to bind a port if the local port is undefined (a.k.a. set to 0). This is a long standing bug which seems to go as far back as v4.0.0-rc.8

## `--legacy-daemon` no longer works as expected

The --legacy-daemon fails with "sshnpd not responding" as of v4.0.4. However, the only thing we do differently between v4.0.3 and v4.0.4 is the following: https://github.com/atsign-foundation/noports/compare/v4.0.3...v4.0.4 (Which is only changes to how we do public key validation).

@gkc thoughts?
@cconstab is all of what I clarified correct?

**Comment by cconstab** [comment]
I think so. Thank you..

**Comment by xavierchanth** [comment]
I just confirmed with sshnp v4.0.4, and it seems that --legacy-daemon is working fine, maybe it was a network timeout @cconstab 

@gkc We still need to fix the port binding issue though

**Comment by cconstab** [comment]
Worked everytime with 3.4.2 never with 4.0.4

So not a timeout issue

**Comment by cconstab** [comment]
https://asciinema.org/a/lmMjGdrbxuHzPkDFqQvYUozJ8
    
This shows both the sshnpd (3.4.2) and sshnp 4.0.4 in action with logging

Shows this is not a timing issue as the two are communicating but the ack is not ack'd becuase I suspect the ack is not something the 3.4.2 shnpd can do ?

**Comment by xavierchanth** [comment]
> ```
> https://asciinema.org/a/lmMjGdrbxuHzPkDFqQvYUozJ8
> ```
> 
> This shows both the sshnpd (3.4.2) and sshnp 4.0.4 in action with logging
> 
> Shows this is not a timing issue as the two are communicating but the ack is not ack'd becuase I suspect the ack is not something the 3.4.2 shnpd can do ?

sshnpd 3.4.2 will ack to an "sshd" message (reverse).

sshnpd 4.0.0 will ack to an "sshd" message (reverse) or an "ssh_request" message (forward)

**Comment by xavierchanth** [comment]
See https://asciinema.org/a/eDzJWWX49Qb04EuyT8OzX73L9
macos-arm64 ^^


What platform / arch are you on @cconstab ?

**Comment by xavierchanth** [comment]
In my tests 4.0.4 only has a problem when -l is not set, but --legacy-daemon works just fine if it is

**Comment by cconstab** [comment]
I am on linux x86
