### ISSUE TITLE
--list-devices and binary version mismatch

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#678]
--list-devices in more recent versions of sshnpd will respond with the noports_core version instead of the sshnpd binary version (as it did previously). We should:

- Include the noports_core version in the usage info for all the binaries (since the noports_core version is what actually determines the capabilities of a particular device)
- Consider including the sshnpd binary version in the --list-devices output

@gkc can I leave this issue to you to look at more closely, since I know you've recently implemented similar capabilities for the SRDs?

**Comment by gkc** [comment]
Fixed by #659
