### ISSUE TITLE
Add configuration option for --no-encrypt-rvd-traffic

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/noports#709]
### Is your feature request related to a problem? Please describe.

 user cannot configure the --no-encrypt-rvd-traffic parameter

### Describe the solution you'd like

 when creating a profile the user should be able to configure the --no-encrypt-rvd-traffic parameter.

**Comment by gkc** [comment]
and
`--authenticate-client-to-rvd`
`--authenticate-device-to-rvd`
`--discover-daemon-features`

**Comment by xavierchanth** [comment]
> --discover-daemon-features

Discover daemon features & list devices will need a custom implementation, since we will want UI feedback instead of command-line output

**Comment by CurtlyCritchlow** [comment]
> > --discover-daemon-features
> 
> Discover daemon features & list devices will need a custom implementation, since we will want UI feedback instead of command-line output

can you elaborate on what you mean by UI feedback? also, I didn't make this ticket a required item to be completed before releasing version on of the desktop app. Is it required before V1 release?

**Comment by xavierchanth** [comment]
> > > --discover-daemon-features
> > 
> > 
> > Discover daemon features & list devices will need a custom implementation, since we will want UI feedback instead of command-line output
> 
> can you elaborate on what you mean by UI feedback? also, I didn't make this ticket a required item to be completed before releasing version on of the desktop app. Is it required before V1 release?

When we --list-devices, it will output a list of sshnpd devices names and the versions to the terminal. For the Desktop App to support this, we would need to implement it differently, but not urgent for the MVP of the app.

**Comment by xavierchanth** [comment]
for now, we need --no-encrypt-rvd-traffic and both --no-authenticate flags
