### ISSUE TITLE
terminal settings broken when using the dart method (5.0.0 issue)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#737]
### Describe the bug

When using the dart implementation (ON LINUX) , the local stty gets screwed up and I have to blindy type `stty sane` to get things back to normal.

### Steps to reproduce

1) Use a command like this `./sshnp -f @cconstab -t @ssh_1 -h @rv_am_beta  -d iot_device01 -i ~/.ssh/GitHub_rsa -u cconstab --no-ad --no-et --ssh-client dart` or `./sshnp -f @cconstab -t @ssh_1 -d tarial  -h @rv_am_beta -u cconstab -i ~/.ssh/GitHub_rsa --ssh-client dart`
2) Connects just fine and commands work fine
3) hit CNTL D to log out
4) The terminal you were is left in a strange state and to get things back you have to blindly type 'stty sane'
5) If you use openssh (default) things work no problem so using `--ssh-client openssh` had no issues e.g. `./sshnp -f @cconstab -t @ssh_1 -d tarial  -h @rv_am_beta -u cconstab -i ~/.ssh/GitHub_rsa`

Situation 
1) Ubuntu machine running sshnp has this issue.

**Note same DOES NOT happen on OSX terminal session so Test via Ubuntu/Linux shell. I also tested using xterm with the same result.

### Expected behavior

tty should be returned to previous (stored) state on exit.

### Screenshots

example

    https://asciinema.org/a/N6g00nyZfHxTlxv4bPyeOtMc6

### Smartphones

Ubuntu Linux

### Were you using an atApplication when the bug was found?

sshnp

### Additional context

*******************       SOLUTION **********************
The terminal needs to be put back to the way it was with something like below. In the ideal world the original settings should be captured and then reset on exit (of any kind)

```
          stdin.lineMode = false;
          stdin.echoMode = false;
          exit(0);
 ```
 
 What the neatest way to do this is unclear to me as there are many exit(<x>) lines in sshnp.dart that all need to do this before exiting.

**Comment by xavierchanth** [comment]
I can tackle this today, should be an easy fix. 
I can add an exit method with steps to reset the terminal session.
