### ISSUE TITLE
Replace sync onDone callback with SyncProgressListener

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/noports#77]
### Is your feature request related to a problem? Please describe.

The sync method which accepts onDone function as a callback to notify the sync completion is deprecated. From now, the sync progress will be notified via the SyncProgressListener.

Following are the files which has onDone usage:

* [bin/sshnpd.dart](https://github.com/atsign-foundation/sshnoports/blob/trunk/bin/sshnpd.dart)
* [bin/sshnp.dart](https://github.com/atsign-foundation/sshnoports/blob/trunk/bin/sshnp.dart)

### Describe the solution you'd like

* Refactor the code to remove the usage of onDone callback in the above-mentioned files and use SyncProgressListener to be notified on the sync progress.

The sample code can be found here: [sync_progress_listener_sample_usage](https://github.com/atsign-foundation/at_client_sdk/blob/trunk/packages/at_client/test/sync_service_test.dart)

**Comment by cconstab** [comment]
This is completed in stream-sshnp branch and will be put in a PR asap
