### ISSUE TITLE
sshnp GUI - looked up sessions unable to close window

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#790]
### Describe the bug

If ssh session fail then the window they are in cannot be closed 

### Steps to reproduce

1. Use the GUI
2. kill the session some how either in the network or the host
3. ssh window hangs and you are unable to close it

### Expected behavior

window closes/can be closed if session closes

### Screenshots

https://github.com/atsign-foundation/noports/assets/6131216/a8b167b7-eb03-45bd-9261-01be8e898e31

### Smartphones

-Windows SSH NP GUI

**Comment by CurtlyCritchlow** [comment]
I believe this is fixed but I'm waiting for @cconstab to re-test V 1.0.0+5 to confirm this issue no longer occurs
