### ISSUE TITLE
More than one manager atSign

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#800]
### Is your feature request related to a problem? Please describe.

Larger teams might want to have a single sshnpd and share access

### Describe the solution you'd like

1 list multple atSigns as mangers at start up

2 have a third atSign that holds a list of managers and is referenced at startup. Centralizing manage control

Using the existing -U opton in sshnp things work just fine

**Comment by gkc** [comment]
Fixed by https://github.com/atsign-foundation/noports/pull/804
