### ISSUE TITLE
Testing Feedback

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/noports#819]
### Is your feature request related to a problem? Please describe.

- [x] First screen has @sign instead of atSign.. 
- [x] Form fields should have a placeholder text in the fields
- [x] Required fields are not indicated
- [x] Change "Select a file" to "Select a Private Key"
- [x] Change add key button text to white.
- [x] Change Submit button text to white
- [x] Set Min and Max screen size on windows
- [x] set app icon for windows

**Support Screen** 

- [x] None of the buttons work on windows
- [x] FAQ goes to Atsign FAQ not NoPorts one

**Settings Screen**

- [x]  When cancel reset app the action it takes you to the welcome screen instead of back to settings.

- [x] Clicked switch Atsign and then the + and I can’t read the buttons or help text, it’s a dark background and dark text. 

**Error message issues**

- [x] Profile name validation typo “field must only use lower case alphanumeric characters spaces” ???

- [x] When privatekey is uploaded check to a valid private key PEM header must start with —- BEGIN

### Describe the solution you'd like

 Fix the bugs

**Comment by CurtlyCritchlow** [comment]
@tinashe404 These fixes were implemented in v1.0.0(4). Please retest and confirm the changes were addressed. If they were please close this ticket.

**Comment by tinashe404** [comment]
Will do!

**Comment by CurtlyCritchlow** [comment]
Closing this ticket, any fixes that were missed will be implement in the next build.
