### ISSUE TITLE
SSH No Ports GUI unable to use Control C

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#820]
### Describe the bug

When using a Linux terminal session Control C and Control V are  useful for cut and pasting and they work in the GUI. But Control C is also used to interupt programs and it is not sent to the terminal session at present.

### Steps to reproduce

1. First I connect to a machine using the GUI
2. Then I run `top`
3. And then I hit Control C  (nothing happens)

### Expected behavior

When something is highlight then Control C copies what is highlighted to the cut/past buffer.

When something is not highlighted then Control C is sent on to the terminal session

### Were you using an atApplication when the bug was found?

- Windows SSH No Ports GUI

### Additional context

What might also be useful is after highlighting right clicking the mouse unhighlights and puts content into cut/paste buffer

**Comment by CurtlyCritchlow** [comment]
@cconstab Do you want control + C to exit from top when nothing is highlighted?

**Comment by xavierchanth** [comment]
> @cconstab Do you want control + C to exit from top when nothing is highlighted?

Yes, he does. if you run top in a normal terminal you can use `q` or `<C-c>` to exit top.
In our app you can only use `q`. 

While this isn't a problem with top, it is a big problem for something like:

`while true; do sleep 1; echo "asdf"; done`

The only way to break that is to kill the tab and load a new session.


In fact, in an ideal world, we pass all control sequences to the terminal:

For example:

`<C-p>` - reloads the previous command
`<C-l>` - clears the screen

**Comment by cconstab** [comment]
When things are highlight cntl c should copy (windows norm)

When nothing is highlighted then the ctnl should be sent to session

**Comment by xavierchanth** [comment]
On windows and linux we can also:
- make <C-C> (Ctrl + shift + c) copy
- make <C-c> (Ctrl + c) send the control signal to the terminal

This is default behaviour of vscode, and I think windows terminal

**Comment by CurtlyCritchlow** [comment]
> On windows and linux we can also:
> 
> * make  (Ctrl + shift + c) copy
> * make  (Ctrl + c) send the control signal to the terminal
> 
> This is default behaviour of vscode, and I think windows terminal

this is working on MacOS when I checked. I'll leave this ticket open until someone else confirms.

**Comment by CurtlyCritchlow** [comment]
Closing this ticket, These features available from build 1.0.0 (4)
