### ISSUE TITLE
updated atSign key flow using APKAM

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#823]
### Is your feature request related to a problem? Please describe.

Moving atkeys file around is pretty ugly and makes instructions difficult to follow when the same atSign is used on multiple devices.
at_activate is probably the most important step and the first and pretty ugly.

### Describe the solution you'd like

Flow in the future would be..
1) Run `at_activate` on your machine to activate your atSigns for both client and device.
2) Run `at_activate` --listen on you machine and `at_activate --pair --device devacename` on the device - Enter OTP , keys generated.
3) Extend `--ls` an `-u` to see the APKAM name (might be different to -d devicename
4) extend at_activate   to be able to delete the APKAM for a particular device i.e `at_activate --deactivate devicename` 

### Describe alternatives you've considered

Include the activation process in the sshnpd binary 

1) Found keys - carryon
2) No keys  and the atSign is not activated then - activate
3) No keys and the atSign is activated - ask do the PKAM thing 

### Additional context

I thought this might be super easy but the APKAM examples in the at_libraries no longer work and have outdated lib calls.

This request is an outline and if the PKAM flow dictates something slightly different not a problem, but using APKAM is the point.

**Comment by gkc** [comment]
@cconstab - @sitaram-kalluri is working on this

**Comment by gkc** [comment]
Examples fixed by https://github.com/atsign-foundation/at_libraries/pull/517

**Comment by cconstab** [comment]
This fix was for tests ? What am i missing ?

**Comment by gkc** [comment]
> This fix was for tests ? What am i missing ?

Note that the ticket is not closed. There's more to do here

**Comment by gkc** [comment]
@cconstab This is a good case for using args 'commands' rather than just flags and options. Commands could be something like the following:
- `onboard` : require atSign, cram
- `spp` : require atSign, spp [, atKeys path] // set the semi-permanent pin
- `enroll` : require atSign, app name, device name, otp [, atKeys path]
  - If atKeys file doesn't exist, then this is a new enrollment
  - If it does exist, then the enrollment request has been made and we need
    to try to auth, and act appropriately on the atServer response (i.e. did
    the auth succeed, or fail because enroll request was denied, or fail
    because it has not yet been approved nor denied, or fail because the
    request has timed out)
- `list-enroll-requests`
- `approve-enroll-request`
- `deny-enroll-request`
- `list-enrollments` [, regex filters for large numbers of enrollments]
- `revoke-enrollment`

wdyt?

**Comment by cconstab** [comment]
I think you are right!

**Comment by gkc** [comment]
About 3SP used in PR81, expect to complete in PR82, remaining effort estimate 2SP

**Comment by gkc** [comment]
No progress in PR82, spent almost all effort in PR82 on https://github.com/atsign-foundation/noports/pull/888

Priority 1 in PR84

**Comment by gkc** [comment]
Some progress in PR84 but not yet complete as spent time on https://github.com/atsign-foundation/noports/issues/855 which is necessary for upcoming demo at event(s).

**Comment by xavierchanth** [comment]
- approve n devices then exit
- approve based on regex / list
- manually approve each one

**Comment by gkc** [comment]
Closing this as complete, all required features complete in the Dart impl, minimum subset of features close to complete in the C impl
