### ISSUE TITLE
default config files are not the most update in the 5.0.2 version the documetation refs more upto date ones 

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#836]
### Describe the bug

The documentation mentions
https://github.com/atsign-foundation/noports/blob/trunk/packages/dart/sshnoports/bundles/shell/systemd/sshnpd.service

Also the other defaults are not updated (which is odd!)

but included file in the release is not the above one

### Steps to reproduce

1. download and install sshnp and try to install systemd method

### Expected behavior

The ref file should be in the release

**Comment by xavierchanth** [comment]
Maybe we should deprecate the inclusion of this file in the releases.

**Comment by xavierchanth** [comment]
This will likely by superseded by #913

**Comment by xavierchanth** [comment]
Removed the config file, and will likely be migrating it to use JSON in the future.
