### ISSUE TITLE
universal.sh / multibuild changes required for 5.1.0 release

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#906]
What I have done:

- laid the foundation for universal.sh script
- updated the multibuild action to update the bound release version for universal.sh and export as an artifact when doing a tagged build
- Added npt to install.sh (the more manual installer)
- Modified the install.sh and bundles to prepare for universal.sh 

What needs doing:
- [x] create a new branch off of trunk
- [x] change the sshnp_version metadata in universal.sh to match the prerelease containing the new bundle format ("5.1.0-rc.5")
- [x] run universal.sh to test and iterate; known issues:
  - [ ] some variables are used when unset in certain flows, you may need to change them from `unset foo` to `foo=''`
    - This is done to ensure we are intentional about the state of variables in the script
  - [x] unarchiving on linux is running into blockers
  - [x] can't assume ~/.local/bin exists
  - [x] can't assume ~/.local/bin is on PATH
  - [x] need to copy binaries to where they'll be run from
  - [x] need to copy template for systemd unit
  - [x] need to copy template for tmux/headless script
  - [x] on linux we assume systemd if we have root access, we should also make sure systemd is installed before trying to use it
- [ ] Add npt to the codesign list in multibuild

**Comment by cpswan** [comment]
Moved to PR84 and 1SP added

**Comment by xavierchanth** [comment]
So we can't use logname, because I've noticed it is not installed everywhere... although it is supposed to be the POSIX compliant solution...

And unlike logname, whoami doesn't give the SUDO_USER which means it also will not suffice for detecting the non-root user running the script.

![Image](https://github.com/atsign-foundation/noports/assets/33691921/6321049c-d21b-460b-9181-48092648c4bc)

**Comment by xavierchanth** [comment]
> So we can't use logname, because I've noticed it is not installed everywhere... although it is supposed to be the POSIX compliant solution...
> 
> And unlike logname, whoami doesn't give the SUDO_USER which means it also will not suffice for detecting the non-root user running the script.
> 
> ![Image](https://private-user-images.githubusercontent.com/33691921/318813550-6321049c-d21b-460b-9181-48092648c4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjc0NTEsIm5iZiI6MTcxMjA2NzE1MSwicGF0aCI6Ii8zMzY5MTkyMS8zMTg4MTM1NTAtNjMyMTA0OWMtZDIxYi00NjBiLTkxODEtNDgwOTI2NDhjNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE0MTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMGUzYzVkNDQyZTRkNjM2NjcxNjFiNThjMGM3OGNhYTJjZjczZWM3NGVmODg2M2E1ZTczMDJjMzFjMTVkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2hQ8bmUevus0RLa-zfjKQj8qOt9KLNU915EQZwmgTk)

we have a non-logname solution for this in install.sh which I reused
