### ISSUE TITLE
multibuild.yaml - riscv64 docker buildx consistently slow to build / hangs

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#915]
### Describe the bug

The riscv64 build often is slow or outright hangs and we usually have to rerun.

### Steps to reproduce

Run a multibuild - see past multibuild runs for examples.

### Expected behavior

We are able to build it in a timely manner so I don't have to decide between doing the following:

- Releasing without risv64 and going back to add it
- Wait for it to complete successfully

**Comment by cpswan** [comment]
We probably shouldn't be packaging RISC-V as if it's production ready until we have stable OS targets (and maybe then also RISC-V support in the Docker Dart image).

**Comment by cpswan** [comment]
@XavierChanth you mentioned that the BuildX builds were OK again. Should we drop this, or maybe split the RISC-V build away from the rest?

**Comment by xavierchanth** [comment]
Yeah, I don't think it was anything we did wrong... I think it was something with the GHA runner.

**Comment by cpswan** [comment]
OK. Next time I'm in that code I might modify it anyway now that we know how to test for latest releases (as I feel it would be better to only build RISC-V for release candidates).
