### ISSUE TITLE
APKAM flow for Noports installation

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#952]
Modify the universal.sh installer so that if the keys are not available on the system, we ask for the atSign, then try to at_activate.

If the atSign is already activated, then we should try to do an apkam enrollment and save the keyfile to the machine.

APKAM example code: https://github.com/atsign-foundation/at_libraries/tree/trunk/packages/at_onboarding_cli/example/apkam_examples

**Comment by xavierchanth** [comment]
Bumping this into triage to work on in this coming sprint

**Comment by gkc** [comment]
Now that APKAM glitches are all ironed out, updated instructions will be ready for review May 14

**Comment by gkc** [comment]
This was completed a long time ago
