### ISSUE TITLE
Remove / disable the tunnel layer from sshnp

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#990]
@gkc would like your thoughts on this.

Needed for #954

**Comment by xavierchanth** [comment]
Not necessarily needed for #954 since #1004 will be added

**Comment by gkc** [comment]
We've had quite a bit of discussion on this; bottom line: now that we have e2e encryption on the sockets themselves, there is no compelling reason to have an initial ssh tunnel over which the user ssh sessions run
